# Generated by Django 4.2 on 2024-05-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
