# Generated by Django 5.0.8 on 2024-08-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproperty',
            old_name='free_rooms',
            new_name='free_beds',
        ),
        migrations.AddField(
            model_name='addproperty',
            name='occupied_beds',
            field=models.IntegerField(default=0),
        ),
    ]
