# Generated by Django 5.0.8 on 2024-08-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0002_rename_free_rooms_addproperty_free_beds_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproperty',
            old_name='free_beds',
            new_name='free_rooms',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='occupied_beds',
        ),
    ]
