# Generated by Django 4.2 on 2024-06-25 08:18

from django.db import migrations, models
import hostelapp20.models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0002_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='govt_id_back',
            field=models.ImageField(null=True, upload_to=hostelapp20.models.upload_to_govt_id_back),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='govt_id_front',
            field=models.ImageField(null=True, upload_to=hostelapp20.models.upload_to_govt_id_front),
        ),
    ]
