# Generated by Django 5.0.8 on 2024-08-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0003_rename_free_beds_addproperty_free_rooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproperty',
            old_name='occupied_rooms',
            new_name='occupied_beds',
        ),
    ]
