# Generated by Django 5.0.8 on 2024-08-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0004_rename_occupied_rooms_addproperty_occupied_beds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproperty',
            name='free_rooms',
        ),
        migrations.RemoveField(
            model_name='addproperty',
            name='occupied_beds',
        ),
    ]
