# Generated by Django 5.0.8 on 2024-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0006_addproperty_free_beds_addproperty_occupied_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='free_rooms',
            field=models.IntegerField(default=0),
        ),
    ]
