# Generated by Django 5.0.8 on 2024-08-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0007_addproperty_free_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproperty',
            name='free_rooms',
        ),
    ]
