# Generated by Django 5.0.8 on 2024-08-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0008_remove_addproperty_free_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproperty',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
