# Generated by Django 5.0.8 on 2024-08-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostelapp20', '0009_addproperty_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproperty',
            name='is_active',
        ),
    ]
